railstutorial: "https://www.railstutorial.org/"
railstutorial_book: "https://www.railstutorial.org/book"
screencasts: "http://screencasts.railstutorial.org/"
rubyonrails: "http://rubyonrails.org/"
railstutorial_contact: " https://www.railstutorial.org/contact"
railstutorial_help: "https://www.railstutorial.org/help"
