railstutorial: "https://www.railstutorial.org/"
railstutorial_book: "https://www.railstutorial.org/book"
screencasts: "http://screencasts.railstutorial.org/"
rubyonrails: "http://rubyonrails.org/"
railstutorial_contact: "https://www.railstutorial.org/contact"
railstutorial_help: "https://www.railstutorial.org/help"
michaelhartl: "http://www.michaelhartl.com/"
news_railstutorial: "http://news.railstutorial.org/"
MAX_NAME_LENGTH: 50
MAX_EMAIL_LENGTH: 255
MIN_PASS: 6
gravatar_for_user: 80
gravatar_for_size: 50
gravatar_emails: "http://gravatar.com/emails"
page: 10
time_reset_expired: 2
microposts_max: 140
picture_size: 5
gravatar_for_size_show: 30
